import Head from "next/head";
import "./globals.css";
import Navbar from "@/containers/navbar/inde";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Reklama Uz</title>
      </Head>
      <body>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
