import "./globals.css";
import Navbar from "@/containers/navbar/index";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { Suspense } from "react";

export const metadata = {
  title: "Reklama Uz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <Suspense fallback={<>Loading...</>}>
          <Navbar />
        </Suspense>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
